channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.3
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.2
  - numpy==2.1.3
  - pandas==2.2.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.17.0
name: mlflow-env
